---
- name: Create NSXT IP address blocks
  vmware.ansible_for_nsxt.nsxt_ip_blocks:
    hostname: "{{ nsxt.manager.hostname }}"
    username: "{{ nsxt.manager.username }}"
    password: "{{ nsxt.manager.password }}"
    validate_certs: false
    display_name: "{{ item.display_name }}"
    cidr: "{{ item.cidr }}"
    state: present
  loop: "{{ nsxt.ip_blocks }}"
