---

- debug: msg="{{tkg_haproxy}}"

- name: Deploy HA Proxy
  community.vmware.vmware_deploy_ovf:
    hostname: "{{ nested_vcenter.ip }}"
    username: "{{ nested_vcenter.username }}"
    password: "{{ nested_vcenter.password }}"
    validate_certs: false
    name: "tkg-haproxy"
    datacenter: "{{ nested_vcenter.datacenter }}"
    cluster: "{{ tanzu_vsphere.vsphere_cluster }}"
    datastore: "{{ tkg_haproxy.datastore }}"
    disk_provisioning: "{{ disk_mode }}"
    networks:
      Management: "{{ tanzu_vsphere.management_port_group }}"
      Workload: "{{ tanzu_vsphere.vds_networking.workload_port_group }}"
      Frontend: "{{ tanzu_vsphere.vds_networking.workload_port_group }}"
    ova: "{{ haproxy_ova }}"
    allow_duplicates: false
    power_on: true
    fail_on_spec_warnings: true
    wait: true
    wait_for_ip_address: true
    inject_ovf_env: true
    properties:
      appliance.root_pwd: "{{ tkg_haproxy.root_pwd }}"
      network.nameservers: "{{ tkg_haproxy.nameservers }} "
      network.management_ip: "{{ tkg_haproxy.management_ip }}/{{ tkg_haproxy.management_subnet_bits }}"
      network.management_gateway: "{{ tkg_haproxy.management_gateway }}"
      network.workload_ip: "{{ tkg_haproxy.workload_ip }}"
      network.workload_gateway: "{{ tkg_haproxy.workload_gateway }}"
      loadbalance.service_ip_range: "{{ tkg_haproxy.service_ip_range }}"
      loadbalance.haproxy_user: "{{ tkg_haproxy.username }}"
      loadbalance.haproxy_pwd: "{{ tkg_haproxy.password }}"
      loadbalance.dataplane_port: "{{ tkg_haproxy.management_port | default(omit) }}"
