---
# Build a list of each datastore to add to each host
- name: Build datastores to add
  set_fact:
    datastores_to_add: >-
      [
      {% for host in nested_hosts %}
      {% if "nfs_datastores" in  nested_clusters[host.nested_cluster] %}
      {% for datastore in nested_clusters[host.nested_cluster].nfs_datastores  %}
      {
        "host_name": "{{ host.ip }}",
        "datastore_name": "{{datastore.datastore_name}}",
        "nfs_server": "{{datastore.nfs_server}}",
        "nfs_path": "{{datastore.nfs_path}}",
      },
      {% endfor %}
      {% endif %}
      {% endfor %}
      ]

- name: Mount NFS3 datastores to ESXi
  community.vmware.vmware_host_datastore:
    hostname: "{{ nested_vcenter.ip }}"
    username: "{{ nested_vcenter.username }}"
    password: "{{ nested_vcenter.password }}"
    validate_certs: false
    datastore_name: "{{ item.datastore_name }}"
    datastore_type: "nfs"
    nfs_server: '{{ item.nfs_server }}'
    nfs_path: '{{ item.nfs_path }}'
    nfs_ro: false
    esxi_hostname: "{{ item.host_name }}"
    state: present
  delegate_to: localhost
  loop: "{{ datastores_to_add }}"
