---
- name: Create Subscribed Library
  community.vmware.vmware_content_library_manager:
    hostname: "{{ nested_vcenter.ip }}"
    username: "{{ nested_vcenter.username }}"
    password: "{{ nested_vcenter.password }}"
    validate_certs: false
    library_name: "{{ tanzu_vsphere.content_library_name }}"
    library_type: subscribed
    subscription_url: "{{ tanzu_vsphere.content_library_url }}"
    update_on_demand: true
    ssl_thumbprint: "{{ tanzu_vsphere.content_library_thumbprint | default(omit) }}"
    datastore_name: "{{ tanzu_vsphere.content_library_datastore }}"
    state: present
  delegate_to: localhost
