---
- name: Super User Block
  block:
    - name: Create temporary certificate directory
      ansible.builtin.tempfile:
        state: directory
        suffix: pi_cert
      register: temp_dir_results

    - ansible.builtin.set_fact:
        tmp_dir={{ temp_dir_results.path }}

    - name: Create temporary certificate file
      ansible.builtin.copy:
        dest: "{{ tmp_dir }}/{{ item.display_name }}.pem"
        content: |
          {{ item.public_key }}
        mode: '660'
      loop: "{{ nsxt.principal_identities }}"

    - name: Register a TKGI Super User
      vmware.ansible_for_nsxt.nsxt_principal_identities:
        hostname: "{{ nsxt.manager.hostname }}"
        username: "{{ nsxt.manager.username }}"
        password: "{{ nsxt.manager.password }}"
        validate_certs: false
        display_name: "{{ item.display_name }}"
        name: "{{ item.display_name }}"
        node_id: "node-1"
        role: "{{ item.role }}"
        certificate_pem_file: "{{ tmp_dir }}/{{ item.display_name }}.pem"
        state: "present"
      register: pi_result
      loop: "{{ nsxt.principal_identities }}"

  always:
    - name: Remove the temp directory
      ansible.builtin.file:
        path: "{{ tmp_dir }}"
        state: absent
      when: tmp_dir is defined
