---
- name: Deploy OVA containing OS and Kubernetes versions for TKGM
  vmware_deploy_ovf:
    hostname: "{{ tanzu_multi_cloud.vsphere_server }}"
    username: "{{ tanzu_multi_cloud.vsphere_username }}"
    password: "{{ tanzu_multi_cloud.vsphere_password }}"
    validate_certs: false
    name: "tkgm-vsphere-base-image-template"
    cluster: "{{ item.key }}"
    datacenter: "{{ tanzu_multi_cloud.vcenter_datacenter }}"
    datastore: "{{ tanzu_multi_cloud.vcenter_datastore }}"
    disk_provisioning: thin
    networks: 
      nic0: "{{ tanzu_multi_cloud.vsphere_network }}"
    ova: "{{ tkgm_os_kubernetes_ova }}"
    allow_duplicates: false
    power_on: false
    fail_on_spec_warnings: false
    wait: false
  delegate_to: localhost
  with_dict: "{{ nested_clusters }}"

- name: Import Base Image Template into vSphere
  vmware_guest:
    hostname: "{{ tanzu_multi_cloud.vsphere_server }}"
    username: "{{ tanzu_multi_cloud.vsphere_username }}"
    password: "{{ tanzu_multi_cloud.vsphere_password }}"
    validate_certs: false
    name: "tkgm-vsphere-base-image-template"
    state: "present"
    is_template: true
  delegate_to: localhost
  with_dict: "{{ nested_clusters }}"
