---
-   name: Deploy VC and Hosts
    hosts: localhost
    gather_facts: False
    tasks:
    -   name: Set the state of a vCenter to poweroff
        vmware_guest_powerstate:
            hostname: "{{ hosting_vcenter.ip }}"
            username: "{{ hosting_vcenter.user }}" 
            password: "{{ hosting_vcenter.password }}" 
            validate_certs: no
            name: "{{ environment_tag }}-vcenter"
            state: powered-off
        delegate_to: localhost
    
    -   name: Set the state of a all ESXi hosts to poweroff
        vmware_guest_powerstate:
            hostname: "{{ hosting_vcenter.ip }}"
            username: "{{ hosting_vcenter.user }}" 
            password: "{{ hosting_vcenter.password }}" 
            validate_certs: no
            name: "{{ environment_tag }}-{{ item.key }}"
            state: powered-off
        delegate_to: localhost
        with_dict: "{{ nested_hosts }}"

    -   name: Remove the vCenter VM
        vmware_guest:
            hostname: "{{ hosting_vcenter.ip }}"
            username: "{{ hosting_vcenter.user }}" 
            password: "{{ hosting_vcenter.password }}" 
            validate_certs: no
            name: "{{ environment_tag }}-vcenter"
            state: absent
        delegate_to: localhost

    -   name: Remove a ESXi hosts VMs
        vmware_guest:
            hostname: "{{ hosting_vcenter.ip }}"
            username: "{{ hosting_vcenter.user }}" 
            password: "{{ hosting_vcenter.password }}" 
            validate_certs: no
            name: "{{ environment_tag }}-{{ item.key }}"
            state: absent
        delegate_to: localhost
        with_dict: "{{ nested_hosts }}"
